# Generated by Django 4.2.7 on 2025-08-01 18:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was soft deleted', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Supplier name', max_length=200)),
                ('contact_person', models.CharField(help_text='Contact person name', max_length=100)),
                ('email', models.EmailField(help_text='Contact email', max_length=254)),
                ('phone', models.CharField(help_text='Contact phone', max_length=20)),
                ('address', models.TextField(help_text='Supplier address')),
                ('website', models.URLField(blank=True, help_text='Supplier website')),
                ('tax_id', models.CharField(blank=True, help_text='Tax identification number', max_length=50)),
                ('payment_terms', models.CharField(blank=True, help_text='Payment terms', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether supplier is active')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='orders_supp_name_553465_idx'), models.Index(fields=['is_active'], name='orders_supp_is_acti_c509ff_idx'), models.Index(fields=['email'], name='orders_supp_email_d60696_idx')],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was soft deleted', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('order_number', models.CharField(help_text='Unique order number', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('ordered', 'Ordered'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='draft', help_text='Order status', max_length=20)),
                ('order_date', models.DateField(help_text='Order date')),
                ('expected_date', models.DateField(help_text='Expected delivery date')),
                ('received_date', models.DateField(blank=True, help_text='Actual received date', null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total order amount', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True, help_text='Order notes')),
                ('approved_at', models.DateTimeField(blank=True, help_text='Approval timestamp', null=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='User who approved the order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_orders', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(help_text='Supplier', on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='orders.supplier')),
                ('warehouse', models.ForeignKey(help_text='Destination warehouse', on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was soft deleted', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('quantity_ordered', models.PositiveIntegerField(help_text='Quantity ordered', validators=[django.core.validators.MinValueValidator(1)])),
                ('quantity_received', models.PositiveIntegerField(default=0, help_text='Quantity received', validators=[django.core.validators.MinValueValidator(0)])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Unit price', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_price', models.DecimalField(decimal_places=2, default=0, help_text='Total price for this item', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True, help_text='Item notes')),
                ('product', models.ForeignKey(help_text='Product', on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_items', to='products.product')),
                ('purchase_order', models.ForeignKey(help_text='Purchase order', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.purchaseorder')),
            ],
            options={
                'verbose_name': 'Purchase Order Item',
                'verbose_name_plural': 'Purchase Order Items',
                'ordering': ['purchase_order', 'product__name'],
                'indexes': [models.Index(fields=['purchase_order', 'product'], name='orders_purc_purchas_26b99d_idx'), models.Index(fields=['quantity_ordered'], name='orders_purc_quantit_20efad_idx'), models.Index(fields=['quantity_received'], name='orders_purc_quantit_0af423_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['order_number'], name='orders_purc_order_n_aeb95c_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['status'], name='orders_purc_status_f227fe_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['order_date'], name='orders_purc_order_d_b4d8d5_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['supplier'], name='orders_purc_supplie_79a335_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['warehouse'], name='orders_purc_warehou_3386a9_idx'),
        ),
    ]
